version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/facebook_scheduler
      - SECRET_KEY=${SECRET_KEY:-facebook-scheduler-secret-key}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - REDIRECT_URI=${REDIRECT_URI:-http://localhost:8000/callback}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=facebook_scheduler
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 