version: '3.8'

services:
  web:
    build: .
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/facebook_scheduler
      - SECRET_KEY=${SECRET_KEY:-facebook-scheduler-secret-key}
      - APP_ID=${FACEBOOK_APP_ID}
      - APP_SECRET=${FACEBOOK_APP_SECRET}
      - REDIRECT_URI=${FACEBOOK_REDIRECT_URI:-http://localhost:8000/callback}
      - FB_SCHEDULING_DAYS=${FB_SCHEDULING_DAYS:-30}
      - FB_SCHEDULING_MINUTES=${FB_SCHEDULING_MINUTES:-10}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./uploads:/app/uploads
      - ./:/app  # Mount the entire application directory
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=facebook_scheduler
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 